# Generated by Django 3.2.3 on 2024-09-30 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ('recipe', 'ingredient'), 'verbose_name': 'ингредиент в рецепте', 'verbose_name_plural': 'Ингредиенты в рецепте'},
        ),
        migrations.AlterModelOptions(
            name='recipetag',
            options={'ordering': ('recipe', 'tag'), 'verbose_name': 'тэг для рецепта', 'verbose_name_plural': 'Тэги для рецепта'},
        ),
    ]
