# Generated by Django 3.2.3 on 2024-10-07 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('id',), 'verbose_name': 'тэг', 'verbose_name_plural': 'Тэги'},
        ),
    ]
