# Generated by Django 3.2.3 on 2024-09-30 10:30

from django.db import migrations, models
import foodgram.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipeingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[foodgram.validators.real_amount], verbose_name='Количество в рецепте'),
        ),
    ]
