# Generated by Django 3.2.3 on 2024-09-27 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_shoprecipe'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_subscriptions',
        ),
    ]
